---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/settings.json
  label: Menu
- type: directory
  path: docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - documentation-page
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn develop
